GET http://localhost:8080/profile?myID=taekimnick&otherID=taekimnick HTTP/1.1

# POST http://localhost:8080/profile/friend HTTP/1.1
# Content-Type: application/json

# {
# 	"myID":"jinkim",
# 	"otherID":"sayi"
# }

# POST http://localhost:8080/profile/block HTTP/1.1
# Content-Type: application/json

# {
# 	"myID":"jinkim",
# 	"otherID":"sayi"
# }

# GET http://localhost:8080/profile HTTP/1.1
# GET http://localhost:8080/profile/all HTTP/1.1

# DELETE http://localhost:8080/profile/clear HTTP/1.1
